In [1]:
import numpy as np

In [4]:
x = [[55, 160], [60, 165], [65, 155], [70, 180], [75, 160]]
y = [0, 0, 1, 0, 1]

좋은 파라미터 찾는 3가지 방법
1. greedy search(탐욕적 탐색), 모든 경우의 수를 다 대입해본다
1. 정규방정식 : LinearRegression
1. 경사하강법 : SGDRegressor에서 구현되어 있습니다. (미분이 되는 식만 사용 가능)

In [5]:
x = np.array(x)
y = np.array(y)
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x, y)
model.coef_, model.intercept_

(array([ 0.05381295, -0.04604317]), 4.453237410071944)

In [6]:
# 과체중 = 몸무게*0.05 + 키*-0.05 + 4.5
y_hat = np.sum(model.coef_*x, axis=1) + model.intercept_
y_hat

array([ 0.04604317,  0.08489209,  0.81438849, -0.0676259 ,  1.12230216])

In [7]:
np.round(y_hat)

array([ 0.,  0.,  1., -0.,  1.])

반올림은 미분이 안되기 때문에 경사하강법에서는 사용할 수 없다.
그래서, 반올림과 성격이 유사하면서 미분이 되는 로지스틱함수(시그모이드) 사용

In [8]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression().fit(x, y)
model.coef_, model.intercept_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(array([[ 0.69926296, -0.2826264 ]]), array([0.01964337]))

In [9]:
y_hat = np.sum(model.coef_*x, axis=1) + model.intercept_
y_hat

array([-6.74111798, -4.6579352 ,  1.66464357, -1.90470163,  7.24414113])

In [10]:
sigmoid = 1/(1+np.exp(-y_hat))
sigmoid

array([0.00117993, 0.00939689, 0.84086036, 0.12957727, 0.99928616])

In [ ]:
#다분류
y_multi_hat = np.matmul(model.coef_, x.T) + np.expand_dims(model.intercept_, axis=1)